### ISSUE TITLE
schematic and homepage GPIO mismatch

### ISSUE THREAD

**Issue by gfilippi** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#11]
Hello, I'm trying to use the GPIO46 and I believe that there is a mismatch between the schematic and the illustration of the board from the home page: https://www.lilygo.cc/products/t-sim7080-s3

could you please clarify which one is correct? it seems to me that for example pin 9 is not matching what is reported on the schematic.

**Comment by lewisxhe** [comment]
oh There is an error in the pin diagram. Thank you for your feedback. Please refer to the board schematic and the silk screen on the board for details
![image](https://user-images.githubusercontent.com/22990954/235340285-11173264-9747-4bbc-b9e7-18c3a93868c0.png)

**Comment by gfilippi** [comment]
I verified each pin manually and it seems to me that the silkscreen is correct, while the schematic is wrong.
Could you please upload the correct schematic that matches the current board?

thanks

**Comment by lewisxhe** [comment]
![image](https://user-images.githubusercontent.com/22990954/235351477-30f29414-3ca1-41fe-985a-4bb558177512.png)
The schematic is not incorrect, and I am certain it is correct

**Comment by gfilippi** [comment]
Hi lewis, on the schematic P2 is exposing CAM_D2 on pin 3 and CAM_D6 on pin 4, but D2 is IO14 and D6 is IO13.

instead on P2 we have IO17 and IO18.

please confirm

**Comment by lewisxhe** [comment]
![image](https://user-images.githubusercontent.com/22990954/235357809-c3793c6b-2d37-4d74-b55e-f7184e73a169.png)

I understand what you mean, but the starting position of the needle arrangement is different, and the understanding is different.

**Comment by lewisxhe** [comment]
In order to reduce misunderstandings, I have reversed the Pin header
