### ISSUE TITLE
PWRKEY PIN

### ISSUE THREAD

**Issue by wenjun1972** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#12]
Hi,

What is the PWRKEY pin ? 7080G pinout tells GPIO41 for PWR, is it correct one? 

I expect to set the PSM mode and wake up the modem by pulling LOW from HIGH, but I read the status of that PIN is always LOW.

Thanks,

Jun

**Comment by wenjun1972** [comment]
Can you point to me any example code to pull low this function pin to exit from PSM status ?

From: Lewis He ***@***.***>
Date: Tuesday, May 2, 2023 at 8:11 AM
To: Xinyuan-LilyGO/LilyGo-T-SIM7080G ***@***.***>
Cc: Jun Wen ***@***.***>, Author ***@***.***>
Subject: Re: [Xinyuan-LilyGO/LilyGo-T-SIM7080G] PWRKEY PIN (Issue #12)

PWRKEY is the power on function pin of PMU, which is not physically connected to ESP32

**Comment by lewisxhe** [comment]
Sorry, I misunderstood, PWRKEY exists and it is connected to IO41, you wake up from PSM mode, you need to pull down PWRKEY, there is a level conversion circuit in the hardware, so you need to set IO41 to HIGH, this When PWRKEY will be LOW

**Comment by lewisxhe** [comment]
If you still have problems, please reopen

**Comment by ibethcompany** [comment]
Hello, I'm using the battery and when the battery runs out or I remove the battery from the board and return it, the program does not start, I have to press the physical PWR button on the board for it to work...

Is there any way to make it so that when the battery dies or I remove it and put it back in, the program will work normally again without having to press the PWR button on the board?

Thank you very much @lewisxhe

**Comment by lewisxhe** [comment]
If you need to connect the battery to automatically power on, it cannot be done on the current hardware

Another way is to modify the hardware. You need to connect the PMU_IRQ and GND in the picture below. At this time, the battery will be connected to the computer and it will automatically start up. However, the disadvantage is that the interrupt signal of the PMU cannot be used.
![image](https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G/assets/22990954/7f68d8b1-619c-4da3-841e-3a286059a0aa)
