### ISSUE TITLE
Can not connect to serial monitor in arduino

### ISSUE THREAD

**Issue by wlueger** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#15]
Hi,

While i can upload a sketch, by holding boot btn, i can not get serial output:
Port monitor error: command 'open' failed: Invalid serial port. Could not connect to COM5 serial port.
on Windows 10!
Arduino IDE: 2.1.0
![image](https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G/assets/33802114/5fd028f0-fe33-4a4f-b1d9-861b98046270)

When in upload mode i see this in the serial monitor (COM5):

16:58:35.414 -> ESP-ROM:esp32s3-20210327
16:58:35.414 -> Build:Mar 27 2021
16:58:35.414 -> rst:0x15 (USB_UART_CHIP_RESET),boot:0x20 (DOWNLOAD(USB/UART0))
16:58:35.414 -> Saved PC:0x40041a7c
16:58:35.414 -> waiting for download
17:01:21.247 -> ESP-ROM:esp32s3-20210327

Any help would be appreciated!

Thanks, W.

**Comment by lewisxhe** [comment]
Please refer to Article 5 in README's TIPS

**Comment by wlueger** [comment]
> Please refer to Article 5 in README's TIPS

@lewisxhe Thank you very much!

Indeed, i set the proper pins for the modem (4,5,41) and get output now!
It seems that the system crashes before any output can be serialised...
This is strange behaviour compared to other boards, it seems that the serial board is handled differently.

Anyway i can proceed now - THX!

W.
