### ISSUE TITLE
Use Bluetooth as console port

### ISSUE THREAD

**Issue by wenjun1972** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#16]
Hi, Lewis,

I know it is not supported to upload firmware to this module through Bluetooth but do you have the example code to use Bluetooth as console port?

Thanks,

Jun

**Comment by lewisxhe** [comment]
see [there](https://github.com/espressif/arduino-esp32/tree/master/libraries%2FBLE%2Fexamples%2FBLE_uart)

**Comment by wenjun1972** [comment]
thank you, will have a try.
