### ISSUE TITLE
Using 7080G with Hologram.io

### ISSUE THREAD

**Issue by dustymac** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#19]
Maybe this is common knowledge, I'm not sure because I'm new to this.  But I finally got this module to work with Hologram.io by doing the following:

**In the example MinimalModemNBIOTExample.ino**

You have to first register the APN information BEFORE trying to connect so make sure this code happens first below

`    //If you do not know APN, please consult the operator or comment out this code
    //comment start
    const char *apn = "hologram";
    modem.sendAT("+CNCFG=0,1,\"", apn, "\"");
    if (modem.waitResponse() != 1) {
        Serial.println("Config apn Failed!");
        return;
    }
    //comment end ..`

**Comment by lewisxhe** [comment]
I've added a comment emphasizing
