### ISSUE TITLE
BL as console port

### ISSUE THREAD

**Issue by wenjun1972** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#2]
Hi, I saw there 4 of BLE5 example codes there, I am considering to connect SIM7080G module through the Bluetooth connectivity as console port to upload my compiled image, and monitor the printout info on my Macbook instead of serial USB cable, can you advise which example is best for my case ? I am using Platformio as the dev tools.

Thanks,

Jun

**Comment by lewisxhe** [comment]
BLE UART See [here](https://github.com/espressif/arduino-esp32/tree/master/libraries/BLE/examples/BLE_uart)
Uploading code using 7080 is currently not possible
