### ISSUE TITLE
Does T-SIM7080G support China Telecom NB-IOT ?

### ISSUE THREAD

**Issue by bootcampiot** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#22]
If yes, what are the APN and NB-IOT band ?

Thanks,

Jun

**Comment by bootcampiot** [comment]
any advise ?

**Comment by lewisxhe** [comment]
Sorry, I'm late. Did you mention a Chinese telecommunications operator? APN: ctnb BAND 8

**Comment by bootcampiot** [comment]
After set AT+COPS=0,0,CHN-CT,9, we finally attached to China Telecom, we can close this case now.
