### ISSUE TITLE
Does the board support built-in JTAG for debugging

### ISSUE THREAD

**Issue by vabatta** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#23]
As the title says, I've seen in the espidf documentation that the s3 have built-in support for debugging (https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-guides/jtag-debugging/index.html#selecting-jtag-adapter).

**Comment by Jason2866** [comment]
Yes, since GPIO 19 and 20 are directly connected to the USB connector.

**Comment by vabatta** [comment]
Ok thanks. I'm figuring out how to make it work. https://github.com/platformio/platform-espressif32/issues/1126
