### ISSUE TITLE
USB connection error

### ISSUE THREAD

**Issue by pascoalfreitas** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#29]
After the board was active for a few days, constantly connected to USB and on battery, the board stopped responding to the serial connection.
At the moment the LED lights up when connected to USB and is also recognized on the PC, but the serial connection does not work.
I've already carried out tests on other computers with different operating systems, but even when connected, it doesn't respond to USB.

**Comment by lewisxhe** [comment]
Please see tip 14

https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G#3%EF%B8%8F%E2%83%A3-tips

**Comment by lewisxhe** [comment]
If you have other questions, please reopen
