### ISSUE TITLE
ATT NBIOT Card Registration Issue

### ISSUE THREAD

**Issue by wenjun1972** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#3]
Hi, I inserted an ATT NBIOT SIM card on 7080G and program the example code "MinimalModemNBIOTExample" through Platformio, whereas, the console port I saw continuously repeat the messages as below:

OK
AT+CGREG?

+CGREG: 0,2

OK
.AT+CEREG?

+CEREG: 0,2

OK
AT+CGREG?

+CGREG: 0,2
........

These messages keep repeating and won't stop, is it normal ? The Blue LED close to CHD keeps blink as well, what does it mean?

In addition, according to ATT NBIOT doc, ATT NB-IoT devices should be setup to use APN "m2mNB16.com.attz", where shall I put it inside the code, line 53 in the code says the APN there is for GPRS.

**Comment by lewisxhe** [comment]
+CGREG: 0,2 This is an action that can only be executed after the APN setting has been registered while searching for signals and waiting for registration. Please refer to the manual for specific command meanings

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G/commit/9ea916e3412e8faa9db61fa6a49753919dec61dc

**Comment by wenjun1972** [comment]
it changed to +CGREG: 0,3 now after programed your updated code, per the AT command spec, "3" means Registration denied, The GPRS service is disabled, the UE is not allowed to attach for GPRS if it is requested by the user.

**Comment by wenjun1972** [comment]
it works well now after registration this SIM in ATT account, thanks !
