### ISSUE TITLE
PMU failure after some time

### ISSUE THREAD

**Issue by gfilippi** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#32]
I have n.5 units that I was testing in 24/7 mode and one unit failed today. 

it was charging the battery (which is now full) but when I checked the board it was "warm" and it is not powering up anymore.
even if I press the power-on button I do not see the 3.3v coming up ... and I do have now 5v from USB (I removed the battery)

how to debug this? how to check if the pmu is dead?

thanks

**Comment by lewisxhe** [comment]
Run this [MinimalPowersExample](https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G/blob/master/examples/MinimalPowersExample/MinimalPowersExample.ino)to see if it works properly and outputs

**Comment by lewisxhe** [comment]
If you have any other questions, please reopen
