### ISSUE TITLE
how to setup PMU to use PWRON as ENABLE signal ?

### ISSUE THREAD

**Issue by gfilippi** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#35]
I added a request also on the repo for XPowers library. From the spec of AXP2101 PMU it is possible to use the PWRON pin as an EN signal, without the need of pressing the button.

please help in understanding how to configure registers so that the board can be powered on this way, meaning simply using a voltage level for on/off operation for use cases where there is no "human intervention" (like a solar powered device in the field)
 
thanks

**Comment by lewisxhe** [comment]
Already replied in XPowersLib. Question will be closed
