### ISSUE TITLE
LilyGo-T-SIM7080G won't turn-on with battery only

### ISSUE THREAD

**Issue by xfiber** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#38]
Dear community, 

I am facing an issue with LilyGo-T-SIM7080G when connected to battery as only power source.
When battery is connected I am not able to turn-on the board.
I've tried ready this:

_"If the power supply of the board cannot be turned on when the battery is connected, please check that the mechanical switch beside the USB is turned to ON, and then press the board PWR for 2 seconds. At this time, the board should start to work"._ 

This does not help at all. Board does not want to turn on.

However, whenever I turn-on the board using USB-C power, and later unplug power from USB-C, board will stay on using battery power source. Whenever I turn off the board and try to start with only battery source connected, board will not turn-on. I always need to "jump start" using usb-c power.

I would appreciate your support.
Thank you.

**Comment by lewisxhe** [comment]
It looks like USB CDC is blocked from starting. Try setting USB CDC ON BOOT = DISABLE
![image](https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G/assets/22990954/22152abd-7f7f-48d4-b3bc-7f3e7a1b9b5b)

**Comment by mathieucarbou** [comment]
@lewisxhe : what is this interface? I am starting a project with these boards and I will have the same need. Thanks:-)

**Comment by mathieucarbou** [comment]
> @lewisxhe : what is this interface? I am starting a project with these boards and I will have the same need. Thanks:-)

Looking at the read me, this is Arduino IDE? Do we have some equivalent flags to pass to the compiler when we use platformio?

Thanks!

**Comment by lewisxhe** [comment]
@mathieucarbou  I already have a note in the platformio.ini file
https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G/blob/07233c2de91e3ee80e98b61416066ef2e677465b/platformio.ini#L56C13-L56C13

**Comment by xfiber** [comment]
> It looks like USB CDC is blocked from starting. Try setting USB CDC ON BOOT = DISABLE ![image](https://private-user-images.githubusercontent.com/22990954/296662897-22152abd-7f7f-48d4-b3bc-7f3e7a1b9b5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1Nzc5MDcsIm5iZiI6MTcwNTU3NzYwNywicGF0aCI6Ii8yMjk5MDk1NC8yOTY2NjI4OTctMjIxNTJhYmQtN2Y3Zi00OGQ0LWIzYmMtN2YzZTdhMWI5YjViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDExMzMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YTI3YWM2ZGIxZjkyMTM1MjhhZWZmOTVmY2U5ZGRlOGM2OTJlYWY1ZjliODFlZDJlMmY2Y2U3ZjI4MzM0NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wYmBP8u_mKVmDejLB5HQps_7MdEG-SIc3TIiE9TExRU)

Thank you! this solved the issue.
However, when this is set as above I am not able to monitor serial port. Is this correct behaviour ?

**Comment by xfiber** [comment]
> > @lewisxhe : what is this interface? I am starting a project with these boards and I will have the same need. Thanks:-)
> 
> Looking at the read me, this is Arduino IDE? Do we have some equivalent flags to pass to the compiler when we use platformio?
> 
> Thanks!

Correct. Framework is Arduino IDE.

**Comment by lewisxhe** [comment]
CDC controls whether to use USBC as print output. If set to Disable, the default Serial output will be directed to GPIO43, GPIO44. This is the QWIIC interface near the SIM7080 battery holder.
