### ISSUE TITLE
how to set the PMU dfault state

### ISSUE THREAD

**Issue by gfilippi** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#39]
I;m using T7080 on a prject that does not need to send data very often and so I disable the modem all the time.

I disable the modem via PMU call, do the sensing part and put the ESP32 in deep sleep.

When the ESP32 is waking up ... the PMU always turn on the modem power, and I need to turn it off immediately.
This is sort of ok .. but I would like to avoid the current spike I get due to the modem turning on for few ms before I shut it down.

is it possible to set the PMU "default state" so that I decide which of the power rails are set?

thanks

**Comment by lewisxhe** [comment]
Do not enable DC3 after waking up from sleep

https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G/blob/07233c2de91e3ee80e98b61416066ef2e677465b/examples/MinimalPowersExample/MinimalPowersExample.ino#L77
