### ISSUE TITLE
Use of camera connector

### ISSUE THREAD

**Issue by spatcho** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#45]
Good day,

Apparently there is a camera connector, I would like a link to what camera could be connected, and I would be more interested to connect i.e. an OLED screen . I could solder connect an i2c screen but using the existing connector would be more convenient.

**Comment by lewisxhe** [comment]
Sure , See here https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G/issues/7

**Comment by spatcho** [comment]
Thanks for the answer but #7 is about i2c conflict with pmu, which is not related to my issue

**Comment by lewisxhe** [comment]
oh ! I thought you were going to connect the OLED screen, here is the link to the camera
https://www.lilygo.cc/products/regular-fisheye-lens?variant=42342393151669
