### ISSUE TITLE
The battery has stopped working

### ISSUE THREAD

**Issue by manzajaro** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#47]
Hi, after several days of testing a code and battery life, it turns out that this morning the battery-only power supply stopped working and I don't understand why.

I'm compiling with these options!

<img width="426" alt="image" src="https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G/assets/6926926/a9764bb1-5634-427a-929c-92ea03d16d03">

I've taken measurements with the multimeter and I can see that the PMU is getting 4.1V.

I've measured all the resistors in the schematic and they give the correct value.

When I run the code connected to the usb cable it works correctly, but as soon as I remove it the device switches off.

The power button works correctly, because when it is powered by usb I press it for X seconds and the device turns off.

I run the following code [MinimalPowersExample](https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G/blob/master/examples/MinimalPowersExample/MinimalPowersExample.ino) to see if the PMU is OK and it returns the following result.

<img width="284" alt="image" src="https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G/assets/6926926/b24553b1-4686-4c35-a895-923a363d07b4">

Can someone help me, thanks

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G/assets/22990954/88481699-04f6-46ba-868e-76f7a5c123b3)
Is the switch turned on?

**Comment by manzajaro** [comment]
Hi @lewisxhe,

The button is on, the battery is on and I have been able to check that the PMU receives 4.1v from the battery.

https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G/assets/6926926/30cd97de-9abf-46dc-b8fc-19a7ff6d2fd1

**Comment by lewisxhe** [comment]
Can you follow the instructions here and remove the diode and then run the MinimalPowersExample to see if the battery prints a connection? Now due to the presence of this diode, the battery connection will print even if the battery is not inserted.

https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G/issues/49

**Comment by manzajaro** [comment]
> Can you follow the instructions here and remove the diode and then run the MinimalPowersExample to see if the battery prints a connection? Now due to the presence of this diode, the battery connection will print even if the battery is not inserted.

I'll do it now and tell you the result.

This is the consumption of the board, when it is switched on and the pwr button is pressed.

<img width="1411" alt="image" src="https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G/assets/6926926/8610c1c2-1042-4bb5-a40e-3e97ca92e235">

Thanks @lewisxhe

**Comment by manzajaro** [comment]
Logs with the diode removed, as you can see it detects well. 1st logs without battery, then inserted and detected.

<img width="287" alt="image" src="https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G/assets/6926926/40c46dfb-5c55-453e-bca4-feabb335b6d1">

**Comment by lewisxhe** [comment]
Can detect battery insertion and removal, but cannot use battery power?

**Comment by manzajaro** [comment]
Correct, the battery alone doesn't start. You've already seen the power consumption measurements of the board.

It stopped working on its own, it was undergoing a test throughout the whole night and the next morning the board wasn't functioning and the battery was charged.

**Comment by lewisxhe** [comment]
As you said, the battery path inside the AXP2101 chip may have been disconnected. Please contact your dealer for after-sales service.
