### ISSUE TITLE
7080 SMS messages to cell phone sample code missing

### ISSUE THREAD

**Issue by StephenPeacock** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#52]
Hi Lewis, first, thank you for the great work your do programming!  You are amazing.  My issue:  is there a simple code (like for the 7000g) that uses SMS to phone?  Only found MQTT, IOT solutions, not  SMS, for the 7080 S3.   Is it even a capability (like the 7000g)?

**Comment by lewisxhe** [comment]
Because SIM7000 and SIM7080 do not have SMS function

**Comment by StephenPeacock** [comment]
Thank you, Lewis.  I looked a bit more carefully at the specs for both.  Will use the MQTT code for Zaphron (to replace Cayenne).  Thanks again for your skillful work on these.
