### ISSUE TITLE
7080 S3 limitations for Africa

### ISSUE THREAD

**Issue by StephenPeacock** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#53]
Lewis, I am trying to get the 7080 S3 to connect via your sample MQTT code to Zaphron in Africa.  Is this an impossible task, and outside of 7080 specs?  Is it a case of the right sort of SIM NB-IoT card alone, or not possible?

If not feasible, what Lilygo version can be used to collect data in Africa (Malawi and Uganda in particular)?

**Comment by lewisxhe** [comment]
As long as your region supports NB-IOT or CAT-M, you can use MQTT. For specific details on how to connect to the server you mentioned, you need to check the platform you are using.

**Comment by StephenPeacock** [comment]
Thank you, Lewis for yet more good advice.  It is really appreciated.
