### ISSUE TITLE
NB-IoT limitaitons

### ISSUE THREAD

**Issue by StephenPeacock** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#54]
Lewis, may I bother you with one last question?  Malawi does not support NB-IoT, so the 7080 S3 will not be useful.  

Malawi does , however, support GPRS, 2G and 3G.  It looks like a GPSR transmission is preferred to gather data and send.

What Lilygo product is best suited for GPSR?

What LilyGo product is best suited for 2G and 3G?

**Comment by lewisxhe** [comment]
I personally recommend the ESP32S3 version of A7670, or SIM7672. Compared with other models, A7670/7672 is easier to use and supports 2/3/4G.
