### ISSUE TITLE
Deep-Sleep Stub

### ISSUE THREAD

**Issue by SFeli** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#57]
Hello,

I have checked all issues (open / closed) and read the informations on github and webpage.
The ESP32S3 supports the very economic way of deep-sleep which only runs the relevant code during wake up phase -
and not restart the whole program. - All relevant code must be in RTC-memory. It would be great, if a measurement and transmission of the data would run in a wake up stub. :-)

Just to start I would like to run the example in github - examples/system/deep_sleep_wake_stub  but this doesn't work as described.
The board always starts from the beginning. Is it the PowerManagement which is not compatible ?

Glad to get your thoughts or in best case a solution.

**Comment by lewisxhe** [comment]
As long as you don't operate the power management chip through I2C, it has nothing to do with the power management chip. I haven't tried the example you mentioned. I think you should raise an issue in esp-idf.
