### ISSUE TITLE
PCB layout file

### ISSUE THREAD

**Issue by al-bleda** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#59]
Sorry, but I don't find the PCB layout file. Is this file available? Is there a way to take a look to it?
Thanks in advance.

**Comment by lewisxhe** [comment]
Are you referring to the source file or the layout component tag and parameter diagram?
The source files cannot be shared, but the originals and bitmaps are ok.

**Comment by al-bleda** [comment]
I mean the PCB layout, with routing wires and/or pads. I've seen the schematic design on pdf. 
I would like to find the PCB layout design, even in pdf.

Thanks in advance.
