### ISSUE TITLE
What are the pins for SDA and SCL ?

### ISSUE THREAD

**Issue by wenjun1972** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#6]
What re the pins for SDA and SLA if we don't use camera ?

We found below list in the readme but not quite understood what it means.

------------------------------------------------------------------
Camera | PWDN | Reset | XCLK | SDA | SCL | VSYNC | HREF | PCLK
GPIO | N/A | 18 | 8 | 2 | 1 | 16 | 17 | 12
Camera | D9 | D8 | D7 | D6 | D5 | D4 | D3 | D2
GPIO | 9 | 10 | 11 | 13 | 21 | 48 | 47 | 14

**Comment by lewisxhe** [comment]
I updated the readme file
