### ISSUE TITLE
Clarifications on tips section

### ISSUE THREAD

**Issue by sporkyduck** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#60]
Hi,

Under 3 Tips, it is stated that "⚠ SIM7080G cannot connect to cellular network and GPS positioning at the same time".
Is there a code example where it is shown best practice for switching between? The most obvious use case would be continously reading GPS data while maintaining a network connection. How is this done in a robust way?

Thanks

**Comment by lewisxhe** [comment]
There is no mention of the best switching method in the SIMCOM manual, but after actual testing, I think the best switching method is to set the modem function to offline mode, that is, AT+CFUN=7, AT+CFUN=4. It's also possible, you can compare
![image](https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G/assets/22990954/8f3fc33e-29ce-49f5-b7f7-e67b564d1298)
