### ISSUE TITLE
WakeUP  not working

### ISSUE THREAD

**Issue by manzajaro** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#72]
I can't get this simple code to work, every time the esp_deep_sleep_start() is executed, it restarts and the reason it says ‘Wakeup caused by external signal using RTC_CNTL’, but I don't have anything connected to the GPIO_NUM_1 pin.

```
void setup() {
  pinMode(GPIO_NUM_1 , INPUT_PULLUP);

  delay(10000);
  esp_sleep_enable_ext1_wakeup(GPIO_NUM_1, ESP_EXT1_WAKEUP_ANY_HIGH);
  delay(500);
  esp_deep_sleep_start();
} 
```

I have tried esp_sleep_enable_ext0_wakeup and it works correctly, but I have already used it for another pin.

Thanks

**Comment by felmue** [comment]
Hello @manzajaro 

well, I think INPUT_PULLUP is enough to trigger the ESP_EXT1_WAKEUP_ANY_HIGH condition.

Thanks
Felix
