### ISSUE TITLE
no start

### ISSUE THREAD

**Issue by famphuelva** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#73]
Linux and windows does not detect the t-sim7080G, I cannot load script, port not recognized

**Comment by famphuelva** [comment]
I have managed to start it,
Connect USB, press boot, press reset, release reset, release boot
A little confusing, but so far everything is ok.

**Comment by Peer77** [comment]
Hi!

The T-SIM7080G board should be recognized flawlessly when using the CH9102 USB drivers, found here:

Windows:
http://www.wch.cn/downloads/CH34xSerCfg_ZIP.html

Linux:
http://www.wch.cn/download/CH341SER_LINUX_ZIP.html

MAC:
http://www.wch.cn/downloads/CH34XSER_MAC_ZIP.html
