### ISSUE TITLE
External power supply with newer version of T-SIM7080?

### ISSUE THREAD

**Issue by romwam** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#79]
I have followed successfully the directions to power the device by external voltage as given in issue
https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G/issues/30 with my first samples of T-SIM7080 last year.

Unforunately on my newer board the diode is not on the board any more and connecting +5V to the indicated diode pad does not power up the board any more.

Please indicate how to power the T-SIM7080 using external 5V voltage for the newer boards where no diode is placed any more.

thank you,

Roman

**Comment by lewisxhe** [comment]
The PCB is exactly the same, just removed the diodes and nothing else changed!

**Comment by lewisxhe** [comment]
Yes

**Comment by romwam** [comment]
Thank you very much for your quick response!
