### ISSUE TITLE
18650 Voltage

### ISSUE THREAD

**Issue by rFlightFPV** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#80]
I might be missing something but I cannot find an (Arduino) example on how to measure the voltage of the 18650 battery when using the LilyGo T-SIM7080G-S3 board? Many thanks in advance for your support.

**Comment by romwam** [comment]
Hi,
i think it is in the MinimalPowers Example, istn't it?
Measuring the battery voltage: https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G/blob/50124a06214b4c8647dd75de50762b6beb72e6dd/examples/MinimalPowersExample/MinimalPowersExample.ino#L218

**Comment by lewisxhe** [comment]
Yes, the pmu example contains

**Comment by rFlightFPV** [comment]
@romwam @lewisxhe thank you both!

**Comment by rFlightFPV** [comment]
@romwam @lewisxhe Thank you both!
