### ISSUE TITLE
Charging battery when power mechanical switch if OFF

### ISSUE THREAD

**Issue by smehner1** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#85]
Hi there,

Currently, the battery is only charged (via USB-C) when the mechanical switch is set to ON. This is not intuitive for the user and may lead to user errors.

I want to operate the LilyGo inside a case and route a charging port to the outside. Ideally, I would like to route the USB-C port to the outside so I can do debugging without having to open the case.

I’ve already found the JST connector for the solar input, but for the power supply (which could be any USB power adapter), I can’t ensure that it limits the charging current to a maximum of 500mA.

Does anyone have any ideas?

Best,

Stefan

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G/issues/49
