### ISSUE TITLE
Percharging and termination current limits

### ISSUE THREAD

**Issue by sporkyduck** [Xinyuan-LilyGO/LilyGo-T-SIM7080G#86]
Hi!

What are the considerations if I would like to increase the constant charging current from 200 mA to a higher value? Will charging the battery with up to 1A work (as the enum __xpowers_axp2101_chg_curr type suggests)?

And, do you need to alter the precharge and termination current limits to match changers in constant charging current?

Thanks
Anders

**Comment by lewisxhe** [comment]
You only need to set the charging current, and the rest does not need to be changed.
